{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "AccountDebitRequestEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "ACCOUNT_DEBIT_REQUEST" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string" },

    { "name": "correlationId", "type": "string" },
    { "name": "transactionId", "type": "string" },
    { "name": "customerId", "type": "string" },
    { "name": "accountId", "type": "string" },
    { "name": "amount", "type": "double" },
    { "name": "description", "type": "string" }
  ]
}