{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "AccountResponseEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "ACCOUNT_RESPONSE" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string" },

    { "name": "correlationId", "type": "string" },

    {
      "name": "error",
      "type": ["null", "string"],
      "default": null
    },

    {
      "name": "account",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Account",
          "fields": [
            { "name": "id", "type": "string" },
            { "name": "customerId", "type": "string" },
            { "name": "productType", "type": "string" },
            { "name": "status", "type": "string" },
            { "name": "balance", "type": "double" },
            { "name": "currency", "type": "string" },
            { "name": "createdAt", "type": "string" }
          ]
        }
      ],
      "default": null
    }
  ]
}
