{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "CardResponseEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "CARD_RESPONSE" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string", "default": "card-service" },

    { "name": "correlationId", "type": "string" },
    { "name": "found", "type": "boolean" },

    { "name": "cardId", "type": "string" },
    { "name": "customerId", "type": "string" },
    { "name": "accountId", "type": "string" },
    { "name": "cardNumber", "type": "string" },
    { "name": "cardType", "type": "string" },
    { "name": "status", "type": "string" }
  ]
}