{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "DebitCardResponseEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "DEBIT_CARD_REQUEST" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string" },

    { "name": "correlationId", "type": "string" },

    { "name": "found", "type": "boolean" },

    {
      "name": "error",
      "type": ["null", "string"],
      "default": null
    },

    {
      "name": "debitCard",
      "type": [
        "null",
        {
          "type": "record",
          "name": "DebitCard",
          "fields": [
            { "name": "id", "type": "string" },
            { "name": "type", "type": "string" },
            { "name": "status", "type": "string" }
          ]
        }
      ],
      "default": null
    }
  ]
}
