{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "NotificationRequestedEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "NOTIFICATION_REQUESTED" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string" },

    { "name": "notificationId", "type": "string" },
    { "name": "customerId", "type": "string" },
    { "name": "recipient", "type": "string" },
    { "name": "channel", "type": "string" },
    { "name": "subject", "type": "string" },
    { "name": "message", "type": "string" }
  ]
}