{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "WalletRequestEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "WALLET_REQUEST" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string" },

    { "name": "correlationId", "type": "string" },

    {
      "name": "walletId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },

    {
      "name": "phone",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}