{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "WalletUpdatedEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "WALLET_UPDATED" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string", "default": "yanki-service" },

    { "name": "walletId", "type": "string" },
    { "name": "phone", "type": "string" },
    { "name": "email", "type": "string" },
    { "name": "debitCardId", "type": "string" },
    { "name": "status", "type": "string" }
  ]
}