{
  "type": "record",
  "name": "WalletPaymentOccurredEvent",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string" },
    { "name": "source", "type": "string" },


    { "name": "correlationId", "type": "string" },

    { "name": "sourceWalletId", "type": "string" },
    { "name": "targetWalletId", "type": "string" },

    { "name": "sourceDebitCardId", "type": "string" },
    { "name": "targetDebitCardId", "type": "string" },

    { "name": "amount", "type": "double" }
  ]
}
