{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "WalletResponseEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "WALLET_RESPONSE" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string", "default": "yanki-service" },

    { "name": "correlationId", "type": "string" },

    { "name": "found", "type": "boolean" },

    { "name": "walletId", "type": "string" },

    { "name": "documentType", "type": "string" },

    { "name": "documentNumber", "type": "string" },

    { "name": "phone", "type": "string" },

    { "name": "imei", "type": "string" },

    { "name": "email", "type": "string" },

    { "name": "debitCardId", "type": "string" },

    { "name": "balance", "type": "double" },

    { "name": "status", "type": "string" }
  ]
}