{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "YankiPaymentFailedEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "YANKI_PAYMENT_FAILED" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string", "default": "yanki-service" },

    { "name": "transactionId", "type": "string" },
    { "name": "sourceWalletId", "type": "string" },
    { "name": "targetWalletId", "type": "string" },
    { "name": "sourcePhone", "type": "string" },
    { "name": "targetPhone", "type": "string" },
    { "name": "amount", "type": "double" },
    { "name": "reason", "type": "string" }
  ]
}